# Generated by Django 4.0.3 on 2022-04-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=200)),
                ('autoridad', models.CharField(max_length=200, null=True)),
                ('logo', models.ImageField(null=True, upload_to='')),
                ('papel_tapiz', models.ImageField(null=True, upload_to='')),
                ('administracion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
